export const cardsDeck = [
  {
    "id": 0,
    "name": "diamondsSeven",
    "suitId": 0,
    "suit": "diamonds",
    "rankId": 0,
    "rank": "seven",
    "trump": false,
    "trumpStrength": 0,
    "score": 0
  },
  {
    "id": 1,
    "name": "diamondsEight",
    "suitId": 0,
    "suit": "diamonds",
    "rankId": 1,
    "rank": "eight",
    "trump": false,
    "trumpStrength": 0,
    "score": 0
  },
  {
    "id": 2,
    "name": "diamondsNine",
    "suitId": 0,
    "suit": "diamonds",
    "rankId": 2,
    "rank": "nine",
    "trump": false,
    "trumpStrength": 0,
    "score": 0
  },
  {
    "id": 3,
    "name": "diamondsTen",
    "suitId": 0,
    "suit": "diamonds",
    "rankId": 3,
    "rank": "ten",
    "trump": false,
    "trumpStrength": 0,
    "score": 10
  },
  {
    "id": 4,
    "name": "diamondsJack",
    "suitId": 0,
    "suit": "diamonds",
    "rankId": 4,
    "rank": "jack",
    "trump": true,
    "trumpStrength": 7,
    "score": 2
  },
  {
    "id": 5,
    "name": "diamondsQueen",
    "suitId": 0,
    "suit": "diamonds",
    "rankId": 5,
    "rank": "queen",
    "trump": true,
    "trumpStrength": 11,
    "score": 3
  },
  {
    "id": 6,
    "name": "diamondsKing",
    "suitId": 0,
    "suit": "diamonds",
    "rankId": 6,
    "rank": "king",
    "trump": false,
    "trumpStrength": 0,
    "score": 4
  },
  {
    "id": 7,
    "name": "diamondsAce",
    "suitId": 0,
    "suit": "diamonds",
    "rankId": 7,
    "rank": "ace",
    "trump": false,
    "trumpStrength": 0,
    "score": 11
  },
  {
    "id": 8,
    "name": "spadesSeven",
    "suitId": 1,
    "suit": "spades",
    "rankId": 0,
    "rank": "seven",
    "trump": false,
    "trumpStrength": 0,
    "score": 0
  },
  {
    "id": 9,
    "name": "spadesEight",
    "suitId": 1,
    "suit": "spades",
    "rankId": 1,
    "rank": "eight",
    "trump": false,
    "trumpStrength": 0,
    "score": 0
  },
  {
    "id": 10,
    "name": "spadesNine",
    "suitId": 1,
    "suit": "spades",
    "rankId": 2,
    "rank": "nine",
    "trump": false,
    "trumpStrength": 0,
    "score": 0
  },
  {
    "id": 11,
    "name": "spadesTen",
    "suitId": 1,
    "suit": "spades",
    "rankId": 3,
    "rank": "ten",
    "trump": false,
    "trumpStrength": 0,
    "score": 10
  },
  {
    "id": 12,
    "name": "spadesJack",
    "suitId": 1,
    "suit": "spades",
    "rankId": 4,
    "rank": "jack",
    "trump": true,
    "trumpStrength": 9,
    "score": 2
  },
  {
    "id": 13,
    "name": "spadesQueen",
    "suitId": 1,
    "suit": "spades",
    "rankId": 5,
    "rank": "queen",
    "trump": true,
    "trumpStrength": 13,
    "score": 3
  },
  {
    "id": 14,
    "name": "spadesKing",
    "suitId": 1,
    "suit": "spades",
    "rankId": 6,
    "rank": "king",
    "trump": false,
    "trumpStrength": 0,
    "score": 4
  },
  {
    "id": 15,
    "name": "spadesAce",
    "suitId": 1,
    "suit": "spades",
    "rankId": 7,
    "rank": "ace",
    "trump": false,
    "trumpStrength": 0,
    "score": 11
  },
  {
    "id": 16,
    "name": "heartsSeven",
    "suitId": 2,
    "suit": "hearts",
    "rankId": 0,
    "rank": "seven",
    "trump": false,
    "trumpStrength": 0,
    "score": 0
  },
  {
    "id": 17,
    "name": "heartsEight",
    "suitId": 2,
    "suit": "hearts",
    "rankId": 1,
    "rank": "eight",
    "trump": false,
    "trumpStrength": 0,
    "score": 0
  },
  {
    "id": 18,
    "name": "heartsNine",
    "suitId": 2,
    "suit": "hearts",
    "rankId": 2,
    "rank": "nine",
    "trump": false,
    "trumpStrength": 0,
    "score": 0
  },
  {
    "id": 19,
    "name": "heartsTen",
    "suitId": 2,
    "suit": "hearts",
    "rankId": 3,
    "rank": "ten",
    "trump": false,
    "trumpStrength": 0,
    "score": 10
  },
  {
    "id": 20,
    "name": "heartsJack",
    "suitId": 2,
    "suit": "hearts",
    "rankId": 4,
    "rank": "jack",
    "trump": true,
    "trumpStrength": 8,
    "score": 2
  },
  {
    "id": 21,
    "name": "heartsQueen",
    "suitId": 2,
    "suit": "hearts",
    "rankId": 5,
    "rank": "queen",
    "trump": true,
    "trumpStrength": 12,
    "score": 3
  },
  {
    "id": 22,
    "name": "heartsKing",
    "suitId": 2,
    "suit": "hearts",
    "rankId": 6,
    "rank": "king",
    "trump": false,
    "trumpStrength": 0,
    "score": 4
  },
  {
    "id": 23,
    "name": "heartsAce",
    "suitId": 2,
    "suit": "hearts",
    "rankId": 7,
    "rank": "ace",
    "trump": false,
    "trumpStrength": 0,
    "score": 11
  },
  {
    "id": 24,
    "name": "clubsSeven",
    "suitId": 3,
    "suit": "clubs",
    "rankId": 0,
    "rank": "seven",
    "trump": true,
    "trumpStrength": 1,
    "score": 0
  },
  {
    "id": 25,
    "name": "clubsEight",
    "suitId": 3,
    "suit": "clubs",
    "rankId": 1,
    "rank": "eight",
    "trump": true,
    "trumpStrength": 2,
    "score": 0
  },
  {
    "id": 26,
    "name": "clubsNine",
    "suitId": 3,
    "suit": "clubs",
    "rankId": 2,
    "rank": "nine",
    "trump": true,
    "trumpStrength": 3,
    "score": 0
  },
  {
    "id": 27,
    "name": "clubsTen",
    "suitId": 3,
    "suit": "clubs",
    "rankId": 3,
    "rank": "ten",
    "trump": true,
    "trumpStrength": 5,
    "score": 10
  },
  {
    "id": 28,
    "name": "clubsJack",
    "suitId": 3,
    "suit": "clubs",
    "rankId": 4,
    "rank": "jack",
    "trump": true,
    "trumpStrength": 10,
    "score": 2
  },
  {
    "id": 29,
    "name": "clubsQueen",
    "suitId": 3,
    "suit": "clubs",
    "rankId": 5,
    "rank": "queen",
    "trump": true,
    "trumpStrength": 14,
    "score": 3
  },
  {
    "id": 30,
    "name": "clubsKing",
    "suitId": 3,
    "suit": "clubs",
    "rankId": 6,
    "rank": "king",
    "trump": true,
    "trumpStrength": 4,
    "score": 4
  },
  {
    "id": 31,
    "name": "clubsAce",
    "suitId": 3,
    "suit": "clubs",
    "rankId": 7,
    "rank": "ace",
    "trump": true,
    "trumpStrength": 6,
    "score": 11
  }
]
